let a=10;
let b=2;
let c="goku";
let d="10";
let e="Goku";
let f=10;
console.log("Double equal to");
console.log(a==b);
console.log(b==c);
console.log(a==d);
console.log(c==e);
console.log("not equal to");
console.log(a!=b);
console.log(b!=c);
console.log(a!=d);
console.log(c!=e);
console.log("triple equal to");
console.log(a===b);
console.log(b===c);
console.log(a===d);
console.log(c===e);
console.log("Not double equal to");
console.log(a!==b);
console.log(b!==c);
console.log(a!==d);
console.log(c!==e);
console.log(a!==f);
